### ISSUE TITLE
invalid LICENSE

### ISSUE THREAD

**Issue by tromp** [AidosKuneen/cuckoo#1]
You seem to have replaced Cuckoo Cycle's FAIR MINING license with a more permissive (MIT) one.

**Comment by ogami-daigoro** [comment]
We believe we don't use any codes from your repo.
If you think it's invalid still, we will think of removing this repo.

You are the author of Cuckoo Cycle, so we are ready to follow your opinions,
but sadly we don't have any plans to use any other licenses except MIT for our newer products.

**Comment by tromp** [comment]
> We don't use any codes from your repo.

No, not literally. I'm not asking you to remove your MIT license. But I would like to see the
FAIR MINING license mentioned in connection with your mean solver port.
Could you please include a comment at the top of mean_miner.go saying:

This mean solver is a rewrite (from C++ to go) of the mean solver of github.com/tromp/cuckoo,
which is covered by the FAIR MINING license.

?
Thanks!
regards,
-John

**Comment by ogami-daigoro** [comment]
We added the comment for
https://github.com/AidosKuneen/cuckoo/blob/master/mean_miner.go
https://github.com/AidosKuneen/cuckoo/blob/master/_simple_miner.go

We appreciate your understanding.
